export const CATEGORY_URL: string = "http://localhost:3000/category"
export const COURSE_URL: string = "http://localhost:3000/course"
export const SUB_URL: string = "http://localhost:3000/sub"
export const POST_URL: string = "http://localhost:3000/post"
export const USER_URL: string = "http://localhost:3000/user"
export const COMMENT_URL: string = "http://localhost:3000/comment"